project:
  type: book
  # output-dir: "Z:/ArcGIS/Epi_Unit_Employee_Handbook/"

book:
  title: "CCDPH Epidemiology Unit Employee Handbook"
  subtitle: "Organizational information and standard procedures for Epidemiology Unit employees"
  cover-image: handbook_cover.png
  author: "CCDPH Epidemiology Unit"
  date: "Last updated 11/2/2023"
  page-navigation: true # true by default (adds previous/next page at bottom of page)
  chapters:
    - index.qmd
    - part: background.qmd
      chapters:
        - organization.qmd # cook county; cch; ccdph; epi unit
        - strategy.qmd # strategic plans, mission, vision
        - people.qmd # profiles/bios of epi unit personnel
        - geography.qmd # cook county; ccdph; scc
    - part: administration.qmd # cch; ccdph
      chapters:
        - calendar.qmd # activity calendar, holidays
        - onboarding.qmd # resources/guide for incoming staff
        - offboarding.qmd # resources/guide for outgoing staff
        - employees.qmd # resources for current staff
        - grants.qmd # application and administration of grants
        - fellowships.qmd # hiring and mentorship of fellows
    - part: data_management.qmd # data management
      chapters:
        - dm_plan_collect.qmd # data management section plan & design / collect & create 
        - dm_analyze_store.qmd # data management section analyze & collaborate / store & manage
        - dm_evaluate_share.qmd # data management section evaluate & Archive / Share & Disseminate
        - dm_access.qmd # data management section Access & Reuse
    - part: epi_data.qmd
      chapters: 
        - primary_data.qmd # primary data collection
        - secondary_data.qmd # secondary data sources and datasets
        - storage.qmd # epi unit datasets, storage, access (database)
        - agreements.qmd # data use agreements (DUAs)
        - processing.qmd # data importing, processing and cleaning
        - analysis.qmd # data analysis; standard calculations/formulas
        - suppression.qmd # data privacy, suppression, rules for reporting
        - dissemination.qmd # health atlas; dashboards; requests; documents
        - indicators.qmd # standard indicators
    - part: project_management.qmd # regular projects
      chapters:
        - programs.qmd # regular/mandated programs (i.e., PHAB reporting; CHA-CHIP)
        - approvals.qmd # project/activity approval process
        - documentation.qmd # description; process; resources
    - part: documents.qmd # categories of documents
      chapters:
        - insights.qmd # characteristics; templates; links
        - databriefs.qmd # characteristics; templates; links
        - reports.qmd # characteristics; templates; links (CHSA)
        - manuscripts.qmd # characteristics; templates; links
        - presentations.qmd # characteristics; templates; links
        - posters.qmd # characteristics; templates; links
    - part: software.qmd # software types, descriptions, installation process
      chapters:
        - github.qmd # github repositories
        - sqlserver.qmd # sql server resources
        - posit.qmd # rstudio resources; code
        - gis.qmd # ArcGIS data, resources; templates
        - sas.qmd # sas resources
        - excel.qmd # excel resources
    - part: learning.qmd # professional development courses, resources
      chapters:
        - training.qmd # required CCH and CCDPH trainings
        - development.qmd # professional development opportunities (linkedin, etc.)
  appendices:
    - references.qmd
    - definitions.qmd
    - acronyms.qmd


bibliography: references.bib

format:
  html:
    theme: [journal, "handbook.scss"]
    favicon: "https://cookcountypublichealth.org/wp-content/uploads/2018/12/cropped-favicon-32x32.png"
    include-in-header: "header.html"
    cache: false
    anchor-sections: true
    smooth-scroll: true
    link-external-icon: true
    link-external-newwindow: true
    page-navigation: true
    echo: true
    eval: false
    warning: false
    code-fold: true
    crossref:
      chapters: true
      
    # number-depth: 3
    # toc-depth: 3
  
editor: source
editor_options: 
  chunk_output_type: console
