# Geography

CCDPH's jurisdiction is within the largely urban Bellwood health region, one of [seven health regions within the state of Illinois](https://dph.illinois.gov/contact-us/regional-health-departments.html). The Bellwood health region, which corresponds with the Cook County boundary, is the smallest of the state's health regions in terms of area, although it has the most residents, comprising over 40 percent of the total population of Illinois.

CCDPH is one of six local health departments within the Bellwood health region. The other five local health departments are the [Chicago Department of Public Health](https://www.chicago.gov/city/en/depts/cdph.html), the [City of Evanston Department of Health and Human Services](https://www.cityofevanston.org/government/departments/health-human-services), the [Village of Oak Park Department of Public Health](https://www.oak-park.us/village-services/department-public-health), the [Stickney Township Public Health District](http://stickneypublichealthdistrict.org/) and the [Village of Skokie Health Department](https://www.skokie.org/158/Health). The [latest contact information for local health departments in Illinois](https://idph.illinois.gov/IDPHPrograms/v_LHDDirectory/Show-V-LHDDirectory-Public.aspx?RegionServed=7) can be found on the Illinois Department of Public Health website.
