# Onboarding {.unnumbered}
Onboarding new employees is the process of integrating them into CCDPH's Epidemiology Unit and setting them up for success in their new roles. Effective onboarding is important for ensuring that new Epidemiology Unit employees are able to quickly become productive and engaged members of the team. The Epidemiology Unit has different types of employees that vary in terms of (inter-institutional) responsibilities, information technology permissions, pay structure, contract scope, management, and employment period. The onboarding process differs in some ways for these roles. This chapter summarizes each of these positions and provide links to the more detailed:

- Health screening: Prior to formalizing employment, prospective employees must...

- Orientation: New employees are welcomed and introduced to the workplace culture and environment via an orientation organized by the broader Cook County Health and Hospital System (CCHHS). The orientation includes an overview of the organization's mission, values, and goals and, if applicable, instructions for logging/swiping in, signing up for health insurance. In addition, the Epidemiology Unit provides a tour of the workplace (e.g., Harrison Square, Bridgeview) and introductions to colleagues. 

- Training: Throughout the first several weeks, new employees receive training to support their work activities. This training may be provided through one-on-one meetings with subject matter experts in the Unit, and, at times, other group training sessions, or online resources.

- Ongoing support: The onboarding process does not end after the first few days or weeks. The Epidemiology Unit provides ongoing support and guidance to new employees as they settle into their roles. Regular check-ins with the Director and feedback sessions through Inter-Epi and cross-training sessions help to ensure that new employees have the resources they need to succeed.

Overall, effective onboarding helps new Epidemiology Unit employees feel welcomed, supported, and prepared to succeed in their new roles, which ultimately benefits CCDPH and CCHHS as a whole.

# Onboarding by employee category

Follow the links below to view additional onboarding information by employee category.

- [CSTE AEF onboarding](https://cookcountypublichealth.org/documents/handbook/in_depth/onboarding_cste_aef.html) 
