# Population {#population .unnumbered}
This chapter describes basic characteristics of Cook County's population, with special attention paid to the conventional reporting geographies used by the Epidemiology Unit, including: (1) SCC; (2) CCDPH's jurisdiction; (3) CCDPH health districts; (4) SCC municipalities; (5) SCC zip code tabulation areas; and (6) census tracts. The chapter goes through dataset creation code steps used to develop suburban Cook County, and other geographies that are used by CCDPH's Epidemiology Unit. The chapter also describes how CCDPH's reference geographic layers are stored and how to access (or import) them via different applications, including R, SAS, and ArcGIS Pro. Note that many of the boundaries discussed in this section change over time due to a variety of reasons including: annexations by cities, re-delineation of administrative and political districts, accuracy updates. A list of the key reference (or base) layers are listed in @fig-spatialtables below.

