# Primary Data {.unnumbered}

Primary data refers to original data that is collected or generated directly from CCDPH for a particular purpose. CCDPH's Epidemiology Unit engages in two primary data collection efforts: (1) the Cook County Health Survey (CCHS), administered annually; (2) the Youth Risk Behavior Survey (YRBS); and (3) School Health Profile Survey (SHPS), CCHS is deployed annually while the later two are administered every two years. The CCDPH has discretion over final design of these surveys, including questions concerning race and ethnicity. @tbl-primesvy shows the overall general purpose of each survey and its funding source.

## Cook County Health Survey (CCHS)

The [Cook County Health Survey (CCHS)](https://cookcountypublichealth.org/health-survey/) is a cross-sectional survey with a sample of approximately 32,000 randomly selected adults aged 18 and older suburban Cook County residents. The paper and web-based versions of the survey are available in English and Spanish. All data collected are self-reported and used to help the CCDPH assess the health-related needs of the county population and to guide the Department in planning programs to improve the health and well being of county residents. The design of the survey including question phrasing and structure closely follows [CDC's national Behavioral Risk Factor Surveillance System](https://www.cdc.gov/brfss/data_documentation/index.htm) (BRFSS) and the [Illinois County Behavioral Risk Factor Surveys](http://www.idph.state.il.us/brfss/countydata.asp?selTopicCounty=R6Overview&areaCounty=Cook_90.1&show=freq&yrCounty=6&form=county&yr=&area=&selTopic=) (ICBRFS) programs. The CCDPH has traditionally sought to align its survey with validated questions asked in the BRFSS, ICBRFS, as well as the similarly structured [Healthy Chicago Survey](https://www.chicago.gov/city/en/depts/cdph/supp_info/healthy-communities/healthy-chicago-survey.html) (HCS) via a broader collaborative effort with the Chicago Department of Public Health (CDPH).

### survey design and implementation

In July 2022, CCDPH sent out 32,000 survey invitations to obtain municipal-level, demographic subgroup, and geographic subgroup information that will be used to inform and monitor the health status of suburban Cook County communities. The CCHS data can be used to provide health, exposure, and health behavior indicator data that can help identify where health disparities exist in suburban Cook County. These indicators will inform policy, program development, community health education initiatives, and public awareness campaigns to address them. Results from the CCHS are shared on the Suburban Cook County Health Atlas and published in reports and briefs. Data are provided for suburban Cook County overall and the over 120 municipalities within CCDPH jurisdiction.

* [Steps for managing, processing and calculating indicators for Cook County Health Survey data](https://justenvirons.org/epihandbook/in_depth/cchs_data_processing.html)

## Youth Risk Behavior Survey (YRBS)

The second primary data collection effort carried out by CCDPH is the [Youth Risk Behavior Survey (YRBS)](https://cookcountypublichealth.org/epidemiology-data-reports/yrbs-youth-risk-behavioral-survey/). Administered in 2010, 2020, and 2022 with plans to administer every two years going forward, the survey assesses health risk behaviors among students (grade 9-12) in participating high schools throughout suburban Cook County. The survey is used to monitor and evaluate a variety of health-related behaviors and conditions among adolescents, including physical activity, sexual behavior, nutrition, alcohol and drug use, and mental health. Survey results can be used to inform the development of health policies and programs that address the needs of adolescents.

* [Steps for managing, processing and calculating indicators for Youth Risk Behavioral Survey data](https://justenvirons.org/epihandbook/in_depth/process_yrbs_data.html)

## School Health Profile Survey (SHPS)

|Survey|Frequency|Funding Source|Purpose|
|:-|:-|:-|:-|
|School Health Profile Survey|Every other year|CDC Health Equity Grant|Schools' health education and health programs and policies assessment|
|Youth Risk Behavioral Survey|Every other year|CDC Health Equity Grant|Assessment of youth risk behaviors that aims to improve health education|
|Cook County Health Survey|Annually|CDC Health Equity Grant|Explore the health conditions, risk factors, and socioeconomic determinants of health|

: Primary Surveys used by the Epidemiology Unit {#tbl-primesvy}