# Secondary Data {.unnumbered}

Secondary data refers to data that has been collected by someone other than CCDPH and is therefore not originally generated by the Epidemiology Unit for a specific purpose. These data can include state (e.g., IDPH) and federal (e.g., from the CDC, Census Bureau, or EPA) government datasets, and many other sources. The Epidemiology Unit uses secondary data to develop public health indicators, and explore relationships between various social, economic, and environmental phenomena. This section briefly summarizes key secondary data sources used by the Epidemiology Unit and provides links to in-depth processing instructions.

```{r}
#| eval: true
#| echo: false

library(DBI)
library(odbc)
library(dplyr)
library(tidyverse)
library(DT)
library(keyring)
library(stringr)
library(openxlsx)
library(data.table)
library(sf)
```

## Vital statistics
Vital statistics refer to the systematic collection, analysis, and interpretation of data related to key life events such as births and deaths, including maternal and fetal deaths. Vital statistics provide critical information about the health of a population. Epidemiologists and public health professionals use vital statistics to track and understand health outcomes. In Illinois, vital records are collected, maintained and distributed by the Illinois Department of Public Health (IDPH) and made available to local health departments including the Cook County Department of Public Health. The vital records received by CCDPH from IDPH include specific information including the residential location of individuals who reside(d) within suburban Cook County. These data are crucial for understanding and monitoring mortality patterns and trends. When stratified by factors such as age, sex, race/ethnicity, and socioeconomic status, the data allows CCDPH epidemiologists to identify disparities in health outcomes and help inform interventions accordingly. Code for collaborating on the processing of vital statistics data irsts managed via the [ccdph-vital-statistics](https://github.com/Cook-County-Department-of-Public-Health/ccdph-vital-statistics) GitHub repository. Links to detailed instructions for processing birth and death records are available via the following links:

* [Steps for requesting, importing, cleaning, coding and transforming mortality or death data](https://justenvirons.org/epihandbook/in_depth/dataprep_mortality_latest_process.html)
* [Steps for requesting, importing, cleaning, coding and transforming natality or birth data](https://justenvirons.org/epihandbook/in_depth/dataprep_natality_latest_process.html)

## Hospital discharge data
Hospital discharge data are administrative data collected when a patient is discharged from a hospital. Inpatient data is collected on patients admitted to a hospital for an overnight stay, while outpatient data is collected on patients who receive services from a hospital but do not stay overnight. The CCDPH receives both [inpatient and outpatient data](https://dph.illinois.gov/topics-services/prevention-wellness/patient-safety-quality/discharge-data.html) from the Illinois Department of Public Health (IDPH) on an irregular basis. The discharge data include patient demographic information, diagnosis codes, procedures codes, charges, among other data. Code for collaborating on the processing of hospital discharge data is managed via the [ccdph-hospital-discharge](https://github.com/Cook-County-Department-of-Public-Health/ccdph-hospital-discharge) GitHub repository. Detailed instructions for processing hospital discharge data are available via the following link:

* [Steps for requesting, importing, cleaning, coding and transforming inpatient and outpatient hospital discharge data](https://justenvirons.org/epihandbook/in_depth/hospital_discharge_latest_process.html)

## Population data from the US Census Bureau
CCDPH epidemiologists rely on US Census data as demographic denominators to calculate public health metrics such as incidence, prevalence, mortality rates, and other key indicators. To calculate incidence and prevalence rates, CCDPH epidemiological staff needs to know the size of the population at risk. US Census data provides detailed population counts and demographic breakdowns by age, gender, race and ethnicity for multiple geographies including suburban Cook County, CCDPH's jurisdiction, health districts, municipalities, zip code tabulation areas (ZCTAs), and census tracts. Similarly, mortality rates (deaths per 1,000 or 100,000 people) require population data from the census to ensure accurate comparisons across different groups. Without census data, public health metrics would lack the context needed to interpret raw health event counts.

Census data is also used by CCDPH epidemiologists to standardize rates to account for differences in population structure. For example, older populations may have higher mortality rates simply because they have more elderly people. Age-adjusted rates, which use census age distribution, enable more accurate comparisons between populations with different age structures. Annualized US decennial census data is used to calculate population trends over time. By comparing health outcomes over time, epidemiologists can track changes in disease rates, mortality, or health behaviors in the context of population growth, aging, or migration.

Code for collaborating on the processing of census data is managed via the [ccdph-data-sets](https://github.com/Cook-County-Department-of-Public-Health/ccdph-data-sets) GitHub repository. Links to detailed instructions for processing American Community Survey (ACS) and decennial census data are available via the following links:

* [Steps for producing annualized population estimates by age, race, sex, SCC, CCDPH, MUNI, 2010-2022](https://justenvirons.org/epihandbook/in_depth/annualized-population-2010-2022-10yr-age-race-sex-scc-ccdph-muni.html)
* [Steps for producing annualized population estimates by sex, ZCTA, 2010-2022](https://justenvirons.org/epihandbook/in_depth/annualized-population-2010-2022-10yr-age-female-zcta.html)


